packages:
    - ./package
    - ./test
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: true

catalogs:
    dep:
        srvx: ~0.11.0
    dev:
        vite: 7.0.0
    peer:
        vite: ^7.0.0 || ^8.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "rolldown-plugin-copy"
    - "ts-vista"
